name: geo-score

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: db-geo-score
    environment:
      POSTGRES_USER: geo
      POSTGRES_PASSWORD: geo
      POSTGRES_DB: geo_score
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geo -d geo_score"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
